runtime: nodejs20
instance_class: F1

# This keeps your costs at $0 by only running 1 "machine"
automatic_scaling:
  max_instances: 1

# This tells Google how to find your homepage
handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)
