runtime: nodejs20
instance_class: F1

# This tells Google to run your main file
entrypoint: node app.js

env_variables:
  # The "Key" we found earlier
  MONGODB_URI: "mongodb+srv://admin:FT2JpgUvQSfzG8Za@frisbeepickup.mrvwtah.mongodb.net/?retryWrites=true&w=majority"
  NODE_ENV: "production"

handlers:
  # If you have a folder for images/css, Google handles it here
  - url: /public
    static_dir: public

  # This sends all other traffic to your app.js logic
  - url: /.*
    script: auto
