runtime: nodejs20
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
# This tells Google: "The homepage is right here in the main list"
- url: /
  static_files: index.html
  upload: index.html

# This tells Google where to find everything else (CSS, images)
- url: /(.*)
  static_files: \1
  upload: (.*)
