runtime: nodejs20
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: RIC3Fam-Hub/index.html
  upload: RIC3Fam-Hub/index.html

- url: /(.*)
  static_files: RIC3Fam-Hub/\1
  upload: RIC3Fam-Hub/(.*)

env_variables:
  MONGO_URI: "YOUR_MONGODB_LINK_HERE"
